### ISSUE TITLE
Showing the emojis in the App

### ISSUE THREAD

**Issue by EightRice** [i-Naji/emojis#13]
Seems like the examples are only demonstrating how to print the emojis to the console, which is super inconsequential. How do you include the elements in the actual UI of the app? Seems like the Emoji type is not a Widget type, so I can't just pass it into the tree. Any clarification would be great.

**Comment by i-Naji** [comment]
It's a **dart** package, not Flutter
`Emoji` class contains emoji's data, `.char` is a Unicode character specified under the Unicode encoding scheme, in Flutter u can easily use it to make widgets and element them in your app.
```dart
final bullseyeEmoji = Emoji.byName('bullseye')!;
final bullseyeWidget = Text(bullseyeEmoji.char);
// or
Text(Emojis.bullseye)
```
